version: '2.1'
services:
  docs-nginx:
    image: docs-nginx
    build: docker/nginx/
    volumes:
      - .:/var/www/
  docs-php:
    image: docs-php
    build: docker/php/
    working_dir: /var/www/
    volumes:
      - .:/var/www/
