openapi: 3.0.0
info:
  title: api
  description: Api
  version: '1.0.0'
servers:
- url: http://127.0.0.1/
  description: 'Development docker-compose'
- url: https://127.0.0.1/
  description: 'Development docker-compose'
tags:
paths:
components:
  parameters:
  schemas:
